### ISSUE TITLE
New study area?

### ISSUE THREAD

**Issue by benjamw** [richiecarmichael/Esri-Hydro-Hierarchy#1]
Hi Richie,

Can this be easily modified to a state-size study area and to include smaller rivers (Strahler < 4)?

I have the rivers of interest from the NHDPlus data set. Should I try to recreate the rivers.js from my area of interest, or can I re-query the Stream Order for streams smaller than 4 and adjust the MBR?

Very cool app!

Thanks

**Comment by richiecarmichael** [comment]
Hi @benjamw,

The feature service used in this app does not include small rivers. Meaning that you would have to publish a new feature service for your state and to the desired level. The trickiest part is tweaking the data to ensure connectivity and correct orientation of the river lines. Finally, use the ArcMap script to generate the json file ("rivers.js").

Thanks for your feedback!

**Comment by benjamw** [comment]
Ok. I guess I'll have to do this the hard way then.  Thanks though.
